### ISSUE TITLE
[WATCH] Refresh Token prefix 고려사항

### ISSUE THREAD

**Issue by CokeLee777** [CokeLee777/spring-security-jwt-auth#15]
## 작업 내용

- [ ] Cookie value에 공백이 안들어가는 문제 해결 요망
- [ ] 공백을 넣을 수 없다면 대응 방안 필요

**Comment by CokeLee777** [comment]
이거 Bearer 넣는걸 고려해보았는데, 그냥 어쩔수 없이 prefix를 빼는거로 가는게 좋을 것 같아요. 어떻게 생각하시나요? @JSY8869

**Comment by JSY8869** [comment]
좋은 것 같습니다~ 딱히 다른 방법이 없는 것 같네요
