### ISSUE TITLE
[DOCS] Advantages and disadvantages of each JWT Token generation library

### ISSUE THREAD

**Issue by JSY8869** [CokeLee777/spring-security-jwt-auth#5]
# 각각의 JWT Token 생성 라이브러리의 장단점 정리
### 장점
- 사용하기 쉽다.
- 가독성이 좋다.
- key 없이 decoding 메서드 지원
### 단점
- java 8, 11, 17에서만 지원함
- ECDSA 알고리즘은 JVM에서 사용하지 말 것(보안 문제)
- 사용자가 적어 자료가 부족하며, 피드백과 보완을 위한 github도 활발하지 않다. (issue가 없을 정도로)
- 공식 자료도 빈약한 편이다.

### 장점
- 고급 기능과 옵션을 제공한다.
- 더 많은 암호화 알고리즘을 제공한다.
- 가장 많은 사용량
- 모든 JDK 및 Android에서 완벽하게 작동
- 공식 자료가 풍부하다.
- github 내에서 issue를 통한 피드백이 활발하게 이루어 지고 있다.
### 단점
- 워낙 유명한 라이브러리기 때문에 spring 내에서도 사용하는 경우가 있고, spring boot 3 사용 시 내부의 jjwt와 사용자가 설치한 jwt 사이의 충돌이 일어나는 경우가 있다고 함(0.00000001% 확률로)
## 결론
jjwt가 훨씬 사용자가 많고, 계속 피드백과 보완이 이루어지고 있고, 커스터마이징이 좋기 때문에 jjwt를 추천합니다.

**Comment by CokeLee777** [comment]
jjwt 의 단점이 내부의 spring 로직중의 jwt 로직하고 jjwt 라이브러리하고 충돌이 일어날 수 있다는 말인가요?

**Comment by JSY8869** [comment]
spring 내부에서 jjwt 라이브러리를 사용하는 부분이 있다고 하는데 설정을 일부러 꼬이게 하는 게 아닌 이상 문제는 없다고 합니다!

**Comment by CokeLee777** [comment]
확인했습니다. jjwt 사용하는거로 합시다
